apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    stage: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      stage: prod
  template:
    metadata:
      labels:
        stage: prod
    spec:
      containers:
      - image: nginx
        name: nginx
